In [1]:
import numpy as np

In [5]:
#3D array

arr = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) #2 x 3 x 2
print(arr, arr.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)


In [6]:
#indexing
print(arr[0,1,1])

4


In [8]:
#slicing
print(arr[:, 0, :]) # first from both colomn
print(arr[:, :, 0]) # first from both colomn

[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]


In [10]:
arr[:, 0, :] = 99
print(arr)

[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]
