In [1]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr ** 2) #square of the array
print(arr + 10) # adding 10 to all numbers in array
print(arr + arr2) #adding both the arrays

[ 1  4  9 16 25]
[11 12 13 14 15]
[ 7  9 11 13 15]
