In [1]:
import numpy as np

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr, type(arr), arr.dtype, arr.shape)

[1 2 3 4 5 6 7] <class 'numpy.ndarray'> int64 (7,)


In [7]:
arr2 = np.array([1, 2, 3, 4, 5, 6, 7, "hello"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

['1' '2' '3' '4' '5' '6' '7' 'hello'] <class 'numpy.ndarray'> <U21 (8,)


In [ ]:
#2d array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [2, 4, 6]])
print(arr2d, arr2d.shape)
# shape means dimension of array
# in 2d array the numbers should be homogenous

[[1 2 3]
 [4 5 6]
 [2 4 6]] (3, 3)
