In [2]:
import numpy as np

In [3]:
#create
arr1 = np.zeros((2,3)) # prefill
print(arr1, arr1.shape)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)


In [9]:
#we can change the value 
arr2 = np.zeros((2,3), dtype = "int64") 
print(arr2, arr2.shape)

[[0 0 0]
 [0 0 0]] (2, 3)


In [10]:
# filling with ones
arr3 = np.ones((2,3), dtype = "int64") 
print(arr3, arr3.shape)

[[1 1 1]
 [1 1 1]] (2, 3)


In [12]:
# full
# in full function we prefill with paticular value
#we can change the value 
arr4 = np.full((3,4), 86) 
print(arr4, arr4.shape)

[[86 86 86 86]
 [86 86 86 86]
 [86 86 86 86]] (3, 4)


In [13]:
# eye
# with eye function an identitiy matrix will be created
# only single value will be passed
#we can change the value 
arr5 = np.eye(2)
print(arr5, arr5.shape)

[[1. 0.]
 [0. 1.]] (2, 2)


In [14]:
# range
# range(start, end, step)
#we can change the value 
arr6 = np.arange(1, 10, 2)
print(arr6, arr6.shape)

[1 3 5 7 9] (5,)


In [15]:
# linspace
# evenly spaced array is created
# linspace(starting value, ending value, no. of elements in array)
arr7 = np.linspace(1, 100, 20)
print(arr7, arr7.shape)

[  1.           6.21052632  11.42105263  16.63157895  21.84210526
  27.05263158  32.26315789  37.47368421  42.68421053  47.89473684
  53.10526316  58.31578947  63.52631579  68.73684211  73.94736842
  79.15789474  84.36842105  89.57894737  94.78947368 100.        ] (20,)
