In [1]:
import numpy as np

In [3]:
# properties of numpy array
arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])

In [4]:
print(arr.shape)

(3, 4)


In [5]:
print(arr.size)

12


In [6]:
print(arr.dtype)

int64


In [7]:
print(arr.ndim)

2


In [9]:
# converting the array type
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

[[ 1.  2.  3.  4.]
 [ 4.  5.  6.  7.]
 [ 7.  8.  9. 10.]] float64
