In [2]:
import numpy as np

In [3]:
# operations on arrays
arr = np.array([[1,2,3],[3,4,5]])
print(arr, arr.shape)

[[1 2 3]
 [3 4 5]] (2, 3)


In [5]:
reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

[[1 2]
 [3 3]
 [4 5]] (3, 2)


In [7]:
# 2D -> 1D
flattened = arr.flatten()
print(flattened, flattened.shape)

[1 2 3 3 4 5] (6,)
