In [1]:
import numpy as np

In [2]:
#fancy indexing
arr3 = np.array([1,2,3,4,5,6,7,8])
idx = [1,3,6]
print(arr3[idx])

[2 4 7]


In [3]:
#boolean indexing
arr4 = np.array([1,2,3,4,5,6,7,8])
print(arr4 > 5)
print(arr4 > 3)
print(arr4 % 2 == 0)

[False False False False False  True  True  True]
[False False False  True  True  True  True  True]
[False  True False  True False  True False  True]


In [4]:
#boolean indexing
arr4 = np.array([1,2,3,4,5,6,7,8])
print(arr4[arr4 > 5])
print(arr4[arr4 > 3])
print(arr4[arr4 % 2 == 0])

[6 7 8]
[4 5 6 7 8]
[2 4 6 8]
